import zipfile
from io import BytesIO
from pathlib import Path
from loguru import logger
from src.domain.entities.project import Boilerplate, ProjectRequest
from src.domain.ports.file_generator import FileGeneratorPort


class ZipFileGenerator(FileGeneratorPort):
    """Adapter for generating ZIP archives"""
    
    def __init__(self):
        # Base path to templates directory
        self.templates_base_path = Path(__file__).parent.parent.parent.parent / "templates"
        # Path to skills directory
        self.skills_base_path = self.templates_base_path / ".agents" / "skills"
        # Path to backend configs directory
        self.backend_configs_path = self.templates_base_path / "backend-configs"
    
    def create_archive(self, boilerplate: Boilerplate, request: ProjectRequest = None) -> BytesIO:
        """Create a ZIP file from boilerplate structure"""
        zip_buffer = BytesIO()
        
        # Track all files to avoid duplicates
        added_files = set()
        
        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
            # First, add AI-generated files (these include updated package.json, etc.)
            logger.info(f"Adding {len(boilerplate.file_structure)} AI-generated files...")
            for file in boilerplate.file_structure:
                zip_file.writestr(file.path, file.content)
                added_files.add(file.path)
            
            # DISABLED: Template base files are now fully generated by AI
            # This prevents copying the entire Clean Architecture template structure
            # if request:
            #     logger.info("Adding template base files (excluding already added)...")
            #     template_files = self._add_template_base_files(zip_file, request, added_files)
            #     added_files.update(template_files)
            
            # Only add ARCHITECTURE.md if not already in file_structure
            if "ARCHITECTURE.md" not in added_files:
                zip_file.writestr(
                    "ARCHITECTURE.md",
                    self._generate_architecture_doc(boilerplate)
                )
                added_files.add("ARCHITECTURE.md")
            
            # Add skills based on tech stack from request
            if request:
                logger.info("Adding AI skills...")
                self._add_skills_to_archive(zip_file, request, added_files)
                # Add backend configuration files (Firebase, Supabase, etc.)
                logger.info("Adding backend configurations...")
                self._add_backend_configs_to_archive(zip_file, request, added_files)
        
        zip_buffer.seek(0)
        return zip_buffer
    
    def _generate_architecture_doc(self, boilerplate: Boilerplate) -> str:
        """Generate architecture documentation"""
        return f"""# {boilerplate.project_metadata.name}

## Architecture Decision

{boilerplate.project_metadata.explanation}

## Stack Type
{boilerplate.project_metadata.stack_type.value}

## Known Limitations
{chr(10).join(f"- {limitation}" for limitation in boilerplate.known_limitations)}

## Focus Areas
{chr(10).join(f"- {area}" for area in boilerplate.cursor_rules.focus_areas)}

---
Generated by VibeArchitect
"""
    
    def _add_skills_to_archive(self, zip_file: zipfile.ZipFile, request: ProjectRequest, added_files: set):
        """Add relevant skills to the archive based on tech preferences from request"""
        skills = self._determine_tech_skills(request)
        
        # Always include core skills
        core_skills = ['accessibility', 'frontend-design', 'seo']
        all_skills = core_skills + skills
        
        # Add each skill folder to the archive
        for skill_name in all_skills:
            skill_path = self.skills_base_path / skill_name
            if skill_path.exists():
                # Add all files in the skill directory
                for file_path in skill_path.rglob('*'):
                    if file_path.is_file():
                        arcname = f".agents/skills/{skill_name}/{file_path.relative_to(skill_path)}"
                        if arcname not in added_files:
                            zip_file.write(file_path, arcname)
                            added_files.add(arcname)
    
    def _determine_tech_skills(self, request: ProjectRequest) -> list[str]:
        """Determine which skills to include based on tech preferences from request"""
        skills = []
        tech_prefs = request.tech_preferences
        
        # Frontend framework
        framework = tech_prefs.framework.lower()
        if 'react' in framework:
            skills.append('react')
        if 'next' in framework:
            skills.append('nextjs')
        if 'astro' in framework:
            skills.append('astro')
        
        # Language
        language = tech_prefs.language.lower()
        if 'typescript' in language:
            skills.append('typescript')
        elif 'javascript' in language:
            skills.append('javascript')
        
        # CSS Framework
        if tech_prefs.css.value == 'tailwind':
            skills.append('tailwind')
        elif tech_prefs.css.value == 'scss':
            skills.append('scss')
        
        # Database
        if tech_prefs.database:
            db = tech_prefs.database.lower()
            if 'postgres' in db or 'postgresql' in db:
                skills.append('postgresql')
            elif 'mongo' in db:
                skills.append('mongodb')
            elif 'mysql' in db:
                skills.append('mysql')
        
        # Backend service
        if tech_prefs.backend_service:
            # Convert enum to string value
            backend = tech_prefs.backend_service.value.lower() if hasattr(tech_prefs.backend_service, 'value') else str(tech_prefs.backend_service).lower()
            if 'firebase' in backend:
                skills.append('firebase')
            elif 'supabase' in backend:
                skills.append('supabase')
            elif 'node' in backend or 'express' in backend:
                skills.append('nodejs')
            elif 'python' in backend or 'fastapi' in backend:
                skills.append('python-fastapi')
        
        return skills
    
    def _add_template_base_files(self, zip_file: zipfile.ZipFile, request: ProjectRequest, added_files: set) -> set:
        """Add base template files (src/, public/, etc.) based on framework and language"""
        tech_prefs = request.tech_preferences
        template_files = set()
        
        # Determine template directory name
        framework = tech_prefs.framework.lower()
        language = tech_prefs.language.lower()
        
        # Map framework + language to template directory
        template_map = {
            ('nextjs', 'typescript'): 'nextjs-ts',
            ('nextjs', 'javascript'): 'nextjs-js',
            ('react', 'typescript'): 'react-ts',
            ('react', 'javascript'): 'react-js',
            ('astro', 'typescript'): 'astro-ts',
            ('astro', 'javascript'): 'astro-js',
        }
        
        # Find matching template
        template_dir_name = None
        for (fw, lang), template_name in template_map.items():
            if fw in framework and lang in language:
                template_dir_name = template_name
                break
        
        if not template_dir_name:
            logger.warning(f"No template found for framework={framework}, language={language}")
            return template_files
        
        template_path = self.templates_base_path / template_dir_name
        
        if not template_path.exists():
            logger.warning(f"Template path does not exist: {template_path}")
            return template_files
        
        logger.info(f"Using template: {template_dir_name}")
        
        # Add all files from the template directory (skip already added)
        file_count = 0
        skipped_count = 0
        for file_path in template_path.rglob('*'):
            if file_path.is_file():
                # Calculate relative path from template directory
                relative_path = file_path.relative_to(template_path)
                archive_path = str(relative_path)
                
                # Skip if already added (AI-generated files take precedence)
                if archive_path in added_files:
                    skipped_count += 1
                    continue
                
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                    zip_file.writestr(archive_path, content)
                    template_files.add(archive_path)
                    file_count += 1
                except Exception as e:
                    logger.warning(f"Could not add {file_path} to archive: {e}")
        
        logger.info(f"Added {file_count} template files from {template_dir_name} (skipped {skipped_count} already present)")
        return template_files
    
    def _add_backend_configs_to_archive(self, zip_file: zipfile.ZipFile, request: ProjectRequest, added_files: set):
        """Add backend configuration files based on selected backend service"""
        tech_prefs = request.tech_preferences
        
        # If no backend service selected, skip backend configs
        if not tech_prefs.backend_service:
            logger.info("No backend service selected, skipping backend configurations")
            return
        
        backend_service = tech_prefs.backend_service.lower()
        language = tech_prefs.language.lower()
        
        logger.info(f"Adding backend configurations for: {backend_service}")
        
        # Map backend services to their config directories
        backend_configs = {
            'firebase': 'firebase',
            'supabase': 'supabase',
        }
        
        # Check if we have configs for this backend service
        if backend_service not in backend_configs:
            logger.warning(f"No backend configs available for: {backend_service}")
            return
        
        config_dir_name = backend_configs[backend_service]
        config_base_path = self.backend_configs_path / config_dir_name / language
        
        if not config_base_path.exists():
            logger.warning(f"Backend config path does not exist: {config_base_path}")
            return
        
        # Add all files from the backend config directory
        file_count = 0
        for file_path in config_base_path.rglob('*'):
            if file_path.is_file():
                # Calculate relative path from config directory
                relative_path = file_path.relative_to(config_base_path)
                
                # Determine destination path in the ZIP
                # For .env files, put them in root
                if file_path.name.startswith('.env'):
                    archive_path = file_path.name
                else:
                    # For other files, put them in src/lib/ directory
                    archive_path = f"src/lib/{relative_path}"
                
                # Skip if already added (avoid duplicates)
                if archive_path in added_files:
                    continue
                
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                    zip_file.writestr(archive_path, content)
                    added_files.add(archive_path)
                    file_count += 1
                except Exception as e:
                    logger.warning(f"Could not add {file_path} to archive: {e}")
        
        logger.info(f"Added {file_count} backend config files for {backend_service}")
    
    def _add_skill_directory(self, zip_file: zipfile.ZipFile, skill_path: Path, skill_name: str) -> None:
        """Recursively add a skill directory and its contents to the ZIP"""
        for item in skill_path.rglob('*'):
            if item.is_file():
                # Calculate relative path from skill directory
                relative_path = item.relative_to(skill_path)
                # Add to .agents/skills/{skill_name}/ in the ZIP
                archive_path = f".agents/skills/{skill_name}/{relative_path}"
                
                try:
                    with open(item, 'r', encoding='utf-8') as f:
                        content = f.read()
                    zip_file.writestr(archive_path, content)
                except Exception as e:
                    # Skip files that can't be read
                    logger.warning(f"Could not add {item} to archive: {e}")
                    pass
